"use strict";
const $=id=>document.getElementById(id);
function fmt(n,d=6){return Number.isFinite(n)?Number(n).toLocaleString("ca-ES",{maximumFractionDigits:d}):String(n)}
function value(id){const el=$(id);if(!el)throw new Error(`Falta el camp ${id}.`);const v=Number(String(el.value).replace(",","."));if(!Number.isFinite(v))throw new Error(`El camp ${id} ha de ser numèric.`);return v}
function positive(v,n){if(!(Number.isFinite(v)&&v>0))throw new Error(`${n} ha de ser positiu.`)}
function nonZero(v,n){if(Math.abs(v)<1e-12)throw new Error(`${n} no pot ser 0.`)}
function render({title,summary,steps=[],extra=""}){const b=$("result");b.innerHTML=`<h2>${title}</h2><p>${summary}</p>${extra}${steps.length?`<div class="proc"><strong>Procediment</strong><ol>${steps.map(s=>`<li>${s}</li>`).join("")}</ol></div>`:""}`;b.scrollIntoView({behavior:"smooth",block:"nearest"})}
function renderError(t,m){render({title:t,summary:`<span class="error">${m}</span>`,steps:["Revisa les dades introduïdes.","Comprova que no hi hagi denominadors zero o valors impossibles."]})}
function showView(id){document.querySelectorAll(".view").forEach(v=>v.classList.toggle("active",v.id===id));document.querySelectorAll(".tab").forEach(b=>b.classList.toggle("active",b.dataset.view===id));window.scrollTo({top:0,behavior:"smooth"})}
document.querySelectorAll(".tab").forEach(b=>b.addEventListener("click",()=>showView(b.dataset.view)));
document.querySelectorAll("[data-jump]").forEach(b=>b.addEventListener("click",()=>showView(b.dataset.jump)));
const COURSES={ "1eso":{title:"1r ESO",focus:["sentit numèric","mesura","geometria bàsica","taules i gràfics"],tools:["Percentatges","Proporcionalitat","Geometria bàsica","Estadística bàsica"],situations:["Organitzem una excursió","Dissenyem una aula","Analitzem una enquesta"]},"2eso":{title:"2n ESO",focus:["fraccions i decimals","percentatges","escales","equacions simples","àrees i volums"],tools:["Equació lineal","Proporcionalitat","Percentatges","Geometria"],situations:["Comparem tarifes","Gestionem un pressupost","Interpretem mapes"]},"3eso":{title:"3r ESO",focus:["funcions","equacions","estadística","probabilitat","geometria analítica inicial"],tools:["Equació quadràtica","Gràfica de funció","Estadística","Geometria"],situations:["Modelem dades amb funcions","Planifiquem una competició","Notícia amb dades"]},"4eso":{title:"4t ESO",focus:["modelització","funcions avançades","trigonometria","sistemes","presa de decisions"],tools:["Gràfiques","Equacions","Trigonometria","Estadística i probabilitat"],situations:["Consum energètic","Dissenyem un envàs","Simulació i presa de decisions"]}};
const SITUATIONS={ excursion:{title:"Organitzem una excursió",context:"Planifiquem una sortida amb transport, entrades, menjar i horaris.",math:["decimals","percentatges","pressupost","proporcionalitat","gràfics"],levels:{1:["Calcula el cost total per alumne.","Ordena despeses.","Comprova el pressupost."],2:["Representa les despeses.","Compara transports.","Calcula un descompte."],3:["Crea una expressió del cost total.","Troba quan una opció surt més barata."],4:["Dissenya una proposta completa i justifica-la."]}}, room:{title:"Dissenyem una aula o habitació",context:"Redistribuïm un espai amb superfícies, mobles, escala i pressupost.",math:["àrees","perímetres","escales","unitats"],levels:{1:["Calcula àrea i perímetre."],2:["Fes un plànol a escala."],3:["Compara distribucions."],4:["Crea un disseny complet."]}}, tariffs:{title:"Comparem tarifes",context:"Dues empreses ofereixen quota fixa i cost variable.",math:["funcions lineals","equacions","gràfiques","punts de tall"],levels:{1:["Calcula costos per consums diferents."],2:["Dibuixa les funcions."],3:["Modelitza cada tarifa."],4:["Argumenta quina tarifa convé."]}}, survey:{title:"Analitzem una enquesta",context:"Recollim dades sobre hàbits o ús del temps.",math:["freqüències","mitjana","mediana","gràfics"],levels:{1:["Organitza dades en taula."],2:["Calcula mitjana, mediana i moda."],3:["Compara dos grups."],4:["Redacta conclusions i detecta biaixos."]}}, energy:{title:"Consum energètic i sostenibilitat",context:"Analitzem el consum d’energia d’una casa o centre.",math:["unitats","funcions","percentatges","gràfics"],levels:{1:["Llegeix una factura."],2:["Calcula percentatges de consum."],3:["Modelitza el cost."],4:["Proposa un pla d’estalvi."]}}, games:{title:"Probabilitat i jocs",context:"Analitzem si un joc és just.",math:["probabilitat","freqüència relativa","combinatòria"],levels:{1:["Enumera casos possibles."],2:["Simula resultats."],3:["Estudia si el joc és just."],4:["Dissenya un joc justificat."]}}};
const FORMULAS={numeric:{label:"Sentit numèric",items:[["Percentatge","p% de A = A·p/100","Descomptes, increments i repartiments."],["Proporcionalitat directa","y = kx","Si x es multiplica, y també."],["Proporcionalitat inversa","xy = k","Producte constant."]]},measure:{label:"Mesura i geometria",items:[["Rectangle","A=b·h; P=2(b+h)","Àrea i perímetre."],["Triangle","A=(b·h)/2","Meitat del rectangle equivalent."],["Cercle","A=πr²; L=2πr","Àrea i longitud."],["Prisma","V=A_base·h","Volum general."],["Cilindre","V=πr²h","Volum del cilindre."]]},algebra:{label:"Àlgebra i funcions",items:[["Equació lineal","ax+b=0 → x=-b/a","Aïllament de la incògnita."],["Equació quadràtica","x=(-b±√(b²-4ac))/(2a)","Fórmula general."],["Funció lineal","f(x)=mx+n","Recta de pendent m."],["Vèrtex paràbola","x_v=-b/(2a)","Màxim o mínim."]]},stochastic:{label:"Estadística i probabilitat",items:[["Mitjana","x̄=Σxᵢ/n","Suma dividida pel nombre de dades."],["Rang","R=max-min","Diferència màxim-mínim."],["Laplace","P(A)=favorables/possibles","Casos equiprobables."],["Unió","P(A∪B)=P(A)+P(B)-P(A∩B)","Evita doble recompte."]]},trig:{label:"Trigonometria",items:[["Raons","sin α=op/hip; cos α=adj/hip; tan α=op/adj","Triangle rectangle."],["Identitat","sin²α+cos²α=1","Relació fonamental."],["Radians","180°=π rad","Conversió d’angles."]]}};
function init(){$("course-select").innerHTML=Object.entries(COURSES).map(([k,c])=>`<option value="${k}">${c.title}</option>`).join("");$("sa-select").innerHTML=Object.entries(SITUATIONS).map(([k,s])=>`<option value="${k}">${s.title}</option>`).join("");$("formula-area").innerHTML=Object.entries(FORMULAS).map(([k,f])=>`<option value="${k}">${f.label}</option>`).join("");updateFormulaItems();updateToolInputs()}init();
$("course-form").addEventListener("submit",e=>{e.preventDefault();const c=COURSES[$("course-select").value];render({title:c.title,summary:"Itinerari recomanat per treballar matemàtiques de manera gradual.",extra:`<div class="badge-row">${c.focus.map(x=>`<span class="badge">${x}</span>`).join("")}</div><h3>Eines recomanades</h3><ul>${c.tools.map(x=>`<li>${x}</li>`).join("")}</ul><h3>Situacions apropiades</h3><ul>${c.situations.map(x=>`<li>${x}</li>`).join("")}</ul>`,steps:["Comença per una situació propera.","Identifica quines eines necessites.","Resol, representa i comprova.","Escriu una conclusió."]})});
$("sa-form").addEventListener("submit",e=>{e.preventDefault();const s=SITUATIONS[$("sa-select").value],l=$("sa-level").value;render({title:s.title,summary:s.context,extra:`<div class="badge-row">${s.math.map(x=>`<span class="badge">${x}</span>`).join("")}</div><h3>Reptes del nivell ${l}</h3><ul>${s.levels[l].map(x=>`<li>${x}</li>`).join("")}</ul>`,steps:["Llegeix el context i subratlla dades.","Decideix si cal calcular, representar, comparar o justificar.","Fes servir una eina si cal.","Comprova si la resposta és raonable."]})});
const TOOL_TEMPLATES={linear:`<label>a<input type="number" id="t-a" value="2" step="any"></label><label>b<input type="number" id="t-b" value="-6" step="any"></label>`,quadratic:`<label>a<input type="number" id="t-a" value="1" step="any"></label><label>b<input type="number" id="t-b" value="-5" step="any"></label><label>c<input type="number" id="t-c" value="6" step="any"></label>`,proportion:`<label>x₁<input type="number" id="t-a" value="3" step="any"></label><label>y₁<input type="number" id="t-b" value="12" step="any"></label><label>x₂<input type="number" id="t-c" value="5" step="any"></label>`,percentage:`<label>Quantitat inicial<input type="number" id="t-a" value="80" step="any"></label><label>Percentatge<input type="number" id="t-b" value="15" step="any"></label>`,geometry:`<label>Figura<select id="t-shape"><option value="rectangle">Rectangle</option><option value="triangle">Triangle</option><option value="circle">Cercle</option><option value="cylinder">Cilindre</option></select></label><label>Mesura A<input type="number" id="t-a" value="8" step="any"></label><label>Mesura B<input type="number" id="t-b" value="3" step="any"></label>`,statistics:`<label>Dades separades per comes<input id="t-list" value="4, 5, 7, 7, 9, 10"></label>`,graph:`<label>Funció<select id="t-fn"><option value="linear">f(x)=mx+n</option><option value="quadratic">f(x)=ax²+bx+c</option></select></label><label>a o m<input type="number" id="t-a" value="1" step="any"></label><label>b o n<input type="number" id="t-b" value="0" step="any"></label><label>c<input type="number" id="t-c" value="-4" step="any"></label>`};
function updateToolInputs(){$("tool-inputs").innerHTML=TOOL_TEMPLATES[$("tool-select").value]||""}
$("tool-select").addEventListener("change",updateToolInputs);
$("tool-form").addEventListener("submit",e=>{e.preventDefault();try{const t=$("tool-select").value;if(t==="linear")solveLinear();if(t==="quadratic")solveQuadratic();if(t==="proportion")solveProportion();if(t==="percentage")solvePercentage();if(t==="geometry")solveGeometry();if(t==="statistics")solveStatistics();if(t==="graph")solveGraph()}catch(err){renderError("No s'ha pogut calcular",err.message)}});
function solveLinear(){const a=value("t-a"),b=value("t-b");nonZero(a,"a");const x=-b/a;render({title:"Equació lineal",summary:`<span class="math">${fmt(a)}x + ${fmt(b)} = 0</span> → <strong>x = ${fmt(x)}</strong>`,steps:["Partim de ax+b=0.","Passem b a l’altre costat.","Dividim per a.",`x=${fmt(-b)}/${fmt(a)}=${fmt(x)}.`]})}
function solveQuadratic(){const a=value("t-a"),b=value("t-b"),c=value("t-c");nonZero(a,"a");const d=b*b-4*a*c;if(d<0){render({title:"Equació quadràtica",summary:`<span class="math">Δ=${fmt(d)}</span>. No hi ha solucions reals.`,steps:["Calculem Δ=b²-4ac.","Com que Δ és negatiu, no hi ha arrels reals."]});return}const x1=(-b+Math.sqrt(d))/(2*a),x2=(-b-Math.sqrt(d))/(2*a);render({title:"Equació quadràtica",summary:`<strong>x₁=${fmt(x1)}</strong>, <strong>x₂=${fmt(x2)}</strong>`,steps:[`Δ=${fmt(d)}.`,"Apliquem la fórmula general.",`x₁=${fmt(x1)}, x₂=${fmt(x2)}.`]})}
function solveProportion(){const x1=value("t-a"),y1=value("t-b"),x2=value("t-c");nonZero(x1,"x₁");const k=y1/x1,y2=k*x2;render({title:"Proporcionalitat directa",summary:`<strong>y₂=${fmt(y2)}</strong>`,steps:["En proporcionalitat directa, y=kx.",`k=${fmt(k)}.`,`y₂=${fmt(k)}·${fmt(x2)}=${fmt(y2)}.`]})}
function solvePercentage(){const base=value("t-a"),pct=value("t-b"),amount=base*pct/100;render({title:"Percentatges",summary:`${fmt(pct)}% de ${fmt(base)} = <strong>${fmt(amount)}</strong>`,steps:["Dividim el percentatge per 100.",`Quantitat=${fmt(base)}·${fmt(pct)}/100=${fmt(amount)}.`,`Increment: ${fmt(base+amount)}. Descompte: ${fmt(base-amount)}.`]})}
function solveGeometry(){const sh=$("t-shape").value,a=value("t-a"),b=value("t-b");positive(a,"Mesura A");let summary="",steps=[];if(sh==="rectangle"){positive(b,"Mesura B");summary=`Àrea=<strong>${fmt(a*b)}</strong>, perímetre=<strong>${fmt(2*(a+b))}</strong>`;steps=["A=base·altura.","P=2(base+altura)."]}if(sh==="triangle"){positive(b,"Mesura B");summary=`Àrea=<strong>${fmt(a*b/2)}</strong>`;steps=["A=base·altura/2."]}if(sh==="circle"){summary=`Àrea=<strong>${fmt(Math.PI*a*a)}</strong>, longitud=<strong>${fmt(2*Math.PI*a)}</strong>`;steps=["A=πr².","L=2πr."]}if(sh==="cylinder"){positive(b,"Mesura B");summary=`Volum=<strong>${fmt(Math.PI*a*a*b)}</strong>`;steps=["V=πr²h."]}render({title:"Geometria",summary,steps})}
function solveStatistics(){const values=$("t-list").value.split(",").map(x=>Number(x.trim().replace(",","."))).filter(Number.isFinite);if(!values.length)throw new Error("Escriu dades separades per comes.");const sorted=[...values].sort((a,b)=>a-b),mean=values.reduce((s,x)=>s+x,0)/values.length,med=sorted.length%2?sorted[(sorted.length-1)/2]:(sorted[sorted.length/2-1]+sorted[sorted.length/2])/2,range=sorted.at(-1)-sorted[0];render({title:"Estadística bàsica",summary:`Mitjana=<strong>${fmt(mean)}</strong>, mediana=<strong>${fmt(med)}</strong>, rang=<strong>${fmt(range)}</strong>`,steps:["Ordenem les dades.","Mitjana: suma/n.","Mediana: valor central.","Rang: màxim-mínim."]})}
function solveGraph(){const kind=$("t-fn").value,a=value("t-a"),b=value("t-b"),c=value("t-c"),id="graph-"+Math.random().toString(36).slice(2);const label=kind==="linear"?`f(x)=${fmt(a)}x+${fmt(b)}`:`f(x)=${fmt(a)}x²+${fmt(b)}x+${fmt(c)}`;render({title:"Gràfica de funció",summary:`<span class="math">${label}</span>`,extra:`<div class="canvas-wrap"><canvas id="${id}" aria-label="Gràfica de funció"></canvas></div>`,steps:["Generem punts entre -10 i 10.","Calculem f(x).","Dibuixem el canvas després de renderitzar-lo."]});requestAnimationFrame(()=>drawFunction(id,x=>kind==="linear"?a*x+b:a*x*x+b*x+c))}
function drawFunction(id,fn){const canvas=$(id);if(!canvas)return;const rect=canvas.getBoundingClientRect(),size=Math.max(320,Math.round(rect.width||720)),dpr=window.devicePixelRatio||1;canvas.width=size*dpr;canvas.height=size*dpr;canvas.style.height=size+"px";const ctx=canvas.getContext("2d");ctx.setTransform(dpr,0,0,dpr,0,0);const W=size,H=size,pad=Math.max(34,Math.round(size*.07)),min=-10,max=10,X=x=>pad+(x-min)/(max-min)*(W-2*pad),Y=y=>H-pad-(y-min)/(max-min)*(H-2*pad);ctx.fillStyle="#fff";ctx.fillRect(0,0,W,H);ctx.strokeStyle="#e2e8f0";ctx.lineWidth=1;for(let i=-10;i<=10;i++){ctx.beginPath();ctx.moveTo(X(i),pad);ctx.lineTo(X(i),H-pad);ctx.stroke();ctx.beginPath();ctx.moveTo(pad,Y(i));ctx.lineTo(W-pad,Y(i));ctx.stroke()}ctx.strokeStyle="#334155";ctx.lineWidth=2;ctx.beginPath();ctx.moveTo(X(0),pad);ctx.lineTo(X(0),H-pad);ctx.stroke();ctx.beginPath();ctx.moveTo(pad,Y(0));ctx.lineTo(W-pad,Y(0));ctx.stroke();ctx.strokeStyle="#1d4ed8";ctx.lineWidth=3;ctx.beginPath();let started=false;for(let i=0;i<=800;i++){const x=min+(max-min)*i/800,y=fn(x);if(!Number.isFinite(y)||y<min*4||y>max*4){started=false;continue}const cx=X(x),cy=Y(Math.max(min,Math.min(max,y)));if(!started){ctx.moveTo(cx,cy);started=true}else ctx.lineTo(cx,cy)}ctx.stroke()}
function updateFormulaItems(){const f=FORMULAS[$("formula-area").value];$("formula-item").innerHTML=f.items.map((item,i)=>`<option value="${i}">${item[0]}</option>`).join("")}
$("formula-area").addEventListener("change",updateFormulaItems);
$("formula-form").addEventListener("submit",e=>{e.preventDefault();const f=FORMULAS[$("formula-area").value],item=f.items[Number($("formula-item").value||0)];render({title:`${f.label}: ${item[0]}`,summary:`<span class="math">${item[1]}</span>`,steps:[item[2],"Identifica cada símbol.","Substitueix dades amb unitats coherents.","Comprova si el resultat és raonable."]})});
$("assessment-form").addEventListener("submit",e=>{e.preventDefault();const checked=[...document.querySelectorAll('input[name="a"]:checked')].length,total=document.querySelectorAll('input[name="a"]').length,pct=Math.round(checked/total*100);const msg=pct>=85?"Procés molt complet.":pct>=60?"Procés força bé, però encara es pot revisar.":"Cal reforçar el procés abans de validar la resposta.";render({title:"Autoavaluació del procés",summary:`<strong>${checked}/${total}</strong> punts · <strong>${pct}%</strong>. ${msg}`,steps:["Una bona resposta no és només un resultat.","Cal entendre, representar, calcular, comprovar i comunicar.","Revisa els punts no marcats."]})});
if("serviceWorker"in navigator){window.addEventListener("load",()=>navigator.serviceWorker.register("./sw.js").catch(console.warn))}


/* V2: situacions d'aprenentatge amb calcul real */
(function(){
  'use strict';
  const $v2=id=>document.getElementById(id);
  const f2=(typeof fmt==='function')?fmt:(n)=>Number(n).toLocaleString('ca-ES',{maximumFractionDigits:6});
  const render2=(typeof render==='function')?render:(p)=>console.log(p);
  const error2=(typeof renderError==='function')?renderError:(t,m)=>console.error(t,m);
  function n2(id){const el=$v2(id);if(!el)throw new Error('Falta el camp '+id+'.');const v=Number(String(el.value).replace(',','.'));if(!Number.isFinite(v))throw new Error('El camp '+id+' ha de ser numèric.');return v;}
  function pos(v,n){if(!(Number.isFinite(v)&&v>0))throw new Error(n+' ha de ser positiu.');}
  function row(a,b){return `<tr><td>${a}</td><td>${b}</td></tr>`;}
  function kpis(items){return `<div class="kpi-grid">${items.map(([l,v])=>`<div class="kpi"><span>${l}</span><strong>${v}</strong></div>`).join('')}</div>`;}
  const templates={
    excursion:`<label>Nombre d’alumnes<input id="sa-a" type="number" value="28" step="1"></label><label>Cost del bus (€)<input id="sa-b" type="number" value="420" step="any"></label><label>Entrada per alumne (€)<input id="sa-c" type="number" value="7.5" step="any"></label><label>Menjar per alumne (€)<input id="sa-d" type="number" value="5" step="any"></label><label>Descompte global (%)<input id="sa-e" type="number" value="10" step="any"></label><label>Pressupost disponible (€)<input id="sa-f" type="number" value="700" step="any"></label>`,
    room:`<label>Llargada de l’espai (m)<input id="sa-a" type="number" value="7.5" step="any"></label><label>Amplada de l’espai (m)<input id="sa-b" type="number" value="4.2" step="any"></label><label>Preu del paviment (€/m²)<input id="sa-c" type="number" value="18" step="any"></label><label>Escala: 1 cm representa... (m)<input id="sa-d" type="number" value="0.5" step="any"></label>`,
    tariffs:`<label>Quota fixa tarifa A (€)<input id="sa-a" type="number" value="8" step="any"></label><label>Preu variable A (€/unitat)<input id="sa-b" type="number" value="0.12" step="any"></label><label>Quota fixa tarifa B (€)<input id="sa-c" type="number" value="3" step="any"></label><label>Preu variable B (€/unitat)<input id="sa-d" type="number" value="0.2" step="any"></label><label>Consum previst<input id="sa-e" type="number" value="80" step="any"></label>`,
    survey:`<label>Dades separades per comes<input id="sa-list" value="4,5,7,7,8,9,9,10,6,7"></label>`,
    energy:`<label>Consum mensual (kWh)<input id="sa-a" type="number" value="250" step="any"></label><label>Preu energia (€/kWh)<input id="sa-b" type="number" value="0.18" step="any"></label><label>Cost fix mensual (€)<input id="sa-c" type="number" value="12" step="any"></label><label>Reducció proposada (%)<input id="sa-d" type="number" value="15" step="any"></label>`,
    games:`<label>Casos favorables<input id="sa-a" type="number" value="2" step="1"></label><label>Casos possibles<input id="sa-b" type="number" value="6" step="1"></label><label>Nombre de partides simulades<input id="sa-c" type="number" value="120" step="1"></label>`
  };
  function update(){const box=$v2('sa-inputs'), sel=$v2('sa-select'); if(box&&sel) box.innerHTML=templates[sel.value]||'<div class="kpi">Aquesta situació encara no té càlcul directe.</div>';}
  function excursion(){const st=n2('sa-a'),bus=n2('sa-b'),ticket=n2('sa-c'),food=n2('sa-d'),disc=n2('sa-e'),budget=n2('sa-f');pos(st,'El nombre d’alumnes');const raw=bus+st*(ticket+food), d=raw*disc/100,total=raw-d,per=total/st,diff=budget-total;render2({title:'SA: Organitzem una excursió',summary:diff>=0?`El pressupost és suficient. Sobren <strong>${f2(diff)} €</strong>.`:`El pressupost no arriba. Falten <strong>${f2(Math.abs(diff))} €</strong>.`,extra:kpis([['Cost total',`${f2(total)} €`],['Cost per alumne',`${f2(per)} €`],['Diferència amb pressupost',`${f2(diff)} €`]])+`<table class="result-table"><tr><th>Concepte</th><th>Valor</th></tr>${row('Bus',`${f2(bus)} €`)}${row('Entrades',`${f2(st*ticket)} €`)}${row('Menjar',`${f2(st*food)} €`)}${row('Descompte',`-${f2(d)} €`)}</table>`,steps:['Calculem el cost variable per alumne: entrada + menjar.','Multipliquem pel nombre d’alumnes.','Sumem el cost fix del bus.','Apliquem el descompte global.','Dividim pel nombre d’alumnes i comparem amb el pressupost.']});}
  function room(){const L=n2('sa-a'),W=n2('sa-b'),price=n2('sa-c'),scale=n2('sa-d');pos(L,'La llargada');pos(W,'L’amplada');pos(scale,'L’escala');const area=L*W,per=2*(L+W),cost=area*price;render2({title:'SA: Dissenyem una aula o habitació',summary:`Àrea = <strong>${f2(area)} m²</strong>, cost estimat = <strong>${f2(cost)} €</strong>.`,extra:kpis([['Àrea',`${f2(area)} m²`],['Perímetre',`${f2(per)} m`],['Cost paviment',`${f2(cost)} €`],['Plànol',`${f2(L/scale)} cm × ${f2(W/scale)} cm`]]),steps:['Àrea = llargada · amplada.','Perímetre = 2·(llargada + amplada).','Cost = àrea · preu per m².','Plànol = mesures reals / escala.']});}
  function tariffs(){const fa=n2('sa-a'),va=n2('sa-b'),fb=n2('sa-c'),vb=n2('sa-d'),x=n2('sa-e');const ca=fa+va*x, cb=fb+vb*x, denom=va-vb;let cut=Math.abs(denom)>1e-12?(fb-fa)/denom:null;const better=ca<cb?'A':cb<ca?'B':'iguals';const id='tariff-'+Math.random().toString(36).slice(2);render2({title:'SA: Comparem tarifes',summary:`Per un consum de ${f2(x)}, la millor opció és: <strong>${better}</strong>.`,extra:kpis([['Cost A',`${f2(ca)} €`],['Cost B',`${f2(cb)} €`],['Millor opció',better],['Punt d’igualtat',cut!==null&&cut>=0?`${f2(cut)} unitats`:'no aplicable']])+`<div class="canvas-wrap"><canvas id="${id}"></canvas></div>`,steps:['Cada tarifa és una funció lineal: cost = quota fixa + preu variable·consum.','Calculem els dos costos.','Resolem el punt d’igualtat.','Dibuixem les dues rectes.']});requestAnimationFrame(()=>drawLines(id,t=>fa+va*t,t=>fb+vb*t,Math.max(100,x*1.3)));}
  function survey(){const el=$v2('sa-list');const a=el.value.split(',').map(x=>Number(x.trim().replace(',','.'))).filter(Number.isFinite);if(!a.length)throw new Error('Escriu dades separades per comes.');const s=[...a].sort((x,y)=>x-y),mean=a.reduce((p,x)=>p+x,0)/a.length,med=s.length%2?s[(s.length-1)/2]:(s[s.length/2-1]+s[s.length/2])/2,range=s.at(-1)-s[0],freq={};a.forEach(x=>freq[x]=(freq[x]||0)+1);const maxF=Math.max(...Object.values(freq)),modes=Object.entries(freq).filter(([k,v])=>v===maxF).map(([k])=>k);const table=`<table class="result-table"><tr><th>Valor</th><th>Freqüència</th></tr>${Object.entries(freq).sort((a,b)=>Number(a[0])-Number(b[0])).map(([k,v])=>row(k,v)).join('')}</table>`;render2({title:'SA: Analitzem una enquesta',summary:`Mitjana = <strong>${f2(mean)}</strong>, mediana = <strong>${f2(med)}</strong>, moda = <strong>${modes.join(', ')}</strong>.`,extra:kpis([['N dades',a.length],['Rang',f2(range)],['Màxim',f2(s.at(-1))],['Mínim',f2(s[0])]])+table,steps:['Ordenem les dades.','Calculem la mitjana.','Busquem la mediana.','Fem la taula de freqüències i la moda.','El rang és màxim menys mínim.']});}
  function energy(){const kwh=n2('sa-a'),price=n2('sa-b'),fixed=n2('sa-c'),red=n2('sa-d');pos(kwh,'El consum');const cost=kwh*price+fixed,newK=kwh*(1-red/100),newC=newK*price+fixed,sav=cost-newC;render2({title:'SA: Consum energètic i sostenibilitat',summary:`Cost actual = <strong>${f2(cost)} €</strong>. Amb la reducció: <strong>${f2(newC)} €</strong>.`,extra:kpis([['Consum actual',`${f2(kwh)} kWh`],['Consum reduït',`${f2(newK)} kWh`],['Estalvi mensual',`${f2(sav)} €`],['Estalvi anual',`${f2(sav*12)} €`]]),steps:['Cost variable = consum · preu per kWh.','Afegim cost fix.','Apliquem la reducció al consum.','Compareu cost inicial i reduït.']});}
  function games(){const fav=n2('sa-a'),poss=n2('sa-b'),tr=n2('sa-c');pos(poss,'Els casos possibles');pos(tr,'El nombre de partides');if(fav<0||fav>poss)throw new Error('Els casos favorables han d’estar entre 0 i els possibles.');const p=fav/poss,exp=p*tr;render2({title:'SA: Probabilitat i jocs',summary:`Probabilitat = <strong>${f2(p*100)}%</strong>. En ${f2(tr)} partides, s’esperen <strong>${f2(exp)}</strong> èxits.`,extra:kpis([['Probabilitat',f2(p)],['Percentatge',`${f2(p*100)}%`],['Freqüència esperada',f2(exp)]]),steps:['Regla de Laplace: favorables / possibles.','Convertim a percentatge.','Multipliquem per les partides per obtenir la freqüència esperada.']});}
  function calc(){const key=$v2('sa-select')?.value;if(key==='excursion')return excursion();if(key==='room')return room();if(key==='tariffs')return tariffs();if(key==='survey')return survey();if(key==='energy')return energy();if(key==='games')return games();throw new Error('Aquesta situació encara no té càlcul directe.');}
  function drawLines(id,A,B,xmax){const cv=$v2(id);if(!cv)return;const rect=cv.getBoundingClientRect(),size=Math.max(320,Math.round(rect.width||720)),dpr=window.devicePixelRatio||1;cv.width=size*dpr;cv.height=size*dpr;cv.style.height=size+'px';const ctx=cv.getContext('2d');ctx.setTransform(dpr,0,0,dpr,0,0);const W=size,H=size,pad=42,xs=Array.from({length:301},(_,i)=>xmax*i/300),ys=xs.flatMap(x=>[A(x),B(x)]),ymax=Math.max(10,...ys)*1.1,X=x=>pad+x/xmax*(W-2*pad),Y=y=>H-pad-y/ymax*(H-2*pad);ctx.fillStyle='#fff';ctx.fillRect(0,0,W,H);ctx.strokeStyle='#e2e8f0';ctx.lineWidth=1;for(let i=0;i<=5;i++){let x=xmax*i/5,y=ymax*i/5;ctx.beginPath();ctx.moveTo(X(x),pad);ctx.lineTo(X(x),H-pad);ctx.stroke();ctx.beginPath();ctx.moveTo(pad,Y(y));ctx.lineTo(W-pad,Y(y));ctx.stroke();}ctx.strokeStyle='#334155';ctx.lineWidth=2;ctx.beginPath();ctx.moveTo(pad,H-pad);ctx.lineTo(W-pad,H-pad);ctx.stroke();ctx.beginPath();ctx.moveTo(pad,pad);ctx.lineTo(pad,H-pad);ctx.stroke();function line(fn,color){ctx.strokeStyle=color;ctx.lineWidth=3;ctx.beginPath();xs.forEach((x,i)=>{const px=X(x),py=Y(fn(x));if(i===0)ctx.moveTo(px,py);else ctx.lineTo(px,py);});ctx.stroke();}line(A,'#1d4ed8');line(B,'#b91c1c');}
  const sel=$v2('sa-select'), form=$v2('sa-form'); if(sel){sel.addEventListener('change',update,true);sel.onchange=update;} update(); if(form){form.addEventListener('submit',e=>{e.preventDefault();e.stopImmediatePropagation();try{calc();}catch(err){error2('No s\'ha pogut calcular la situació.',err.message);}},true);}
})();
